# Generated by Django 3.0.8 on 2020-07-15 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DjangoClasses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=60)),
                ('courseNumber', models.IntegerField()),
                ('instructorName', models.CharField(blank=True, default='', max_length=60, null=True)),
                ('price', models.DecimalField(decimal_places=1, default=0.0, max_digits=100)),
            ],
        ),
    ]
