# Generated by Django 3.0.8 on 2020-07-15 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='djangoclasses',
            old_name='price',
            new_name='duration',
        ),
    ]
