# Generated by Django 2.2.5 on 2020-08-21 01:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=5)),
                ('name', models.CharField(blank=True, default='', max_length=50)),
                ('category', models.CharField(blank=True, default='', max_length=50)),
                ('link', models.CharField(blank=True, default='', max_length=200)),
                ('notes', models.TextField(blank=True, default='', max_length=300)),
                ('watch', models.BooleanField()),
            ],
            options={
                'verbose_name_plural': 'Stocks',
            },
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('open', models.DateField(blank=True, null=True)),
                ('close', models.DateField(blank=True, null=True)),
                ('openCost', models.DecimalField(decimal_places=2, max_digits=7)),
                ('closeCost', models.DecimalField(decimal_places=2, max_digits=7)),
                ('paper', models.BooleanField()),
                ('stock', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='InvestmentApp.Stock')),
            ],
        ),
    ]
