# Generated by Django 2.2.5 on 2020-08-21 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InvestmentApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='category',
            field=models.CharField(blank=True, choices=[('S', 'Stock'), ('M', 'Mutual Fund'), ('I', 'Index Fund')], default='', max_length=1),
        ),
    ]
