# Generated by Django 2.2.5 on 2020-08-21 02:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('InvestmentApp', '0002_auto_20200820_1839'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trade',
            options={'ordering': ['open'], 'verbose_name_plural': 'Trades'},
        ),
        migrations.RemoveField(
            model_name='trade',
            name='closeCost',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='openCost',
        ),
        migrations.AddField(
            model_name='trade',
            name='close_cost',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True, verbose_name='Close per Share'),
        ),
        migrations.AddField(
            model_name='trade',
            name='open_cost',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True, verbose_name='Open per Share'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='category',
            field=models.CharField(choices=[('S', 'Stock'), ('M', 'Mutual Fund'), ('I', 'Index Fund')], default='S', max_length=1),
        ),
        migrations.AlterField(
            model_name='stock',
            name='link',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Website'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='name',
            field=models.CharField(default='', max_length=50, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='notes',
            field=models.TextField(blank=True, default='', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='symbol',
            field=models.CharField(max_length=5, verbose_name='Symbol'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='watch',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='trade',
            name='close',
            field=models.DateField(null=True, verbose_name='Close Date'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='open',
            field=models.DateField(null=True, verbose_name='Open Date'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='paper',
            field=models.BooleanField(default=False, verbose_name='Paper Trade'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='quantity',
            field=models.IntegerField(verbose_name='Number of Shares'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InvestmentApp.Stock'),
        ),
    ]
