# Generated by Django 2.2.5 on 2020-08-22 00:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InvestmentApp', '0004_auto_20200821_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='category',
            field=models.CharField(choices=[('S', 'Stock'), ('M', 'Mutual Fund'), ('I', 'Index Fund')], default='S', max_length=1, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='notes',
            field=models.TextField(blank=True, default='', max_length=300, null=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='watch',
            field=models.BooleanField(default=True, verbose_name='Watch List'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='close_cost',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True, verbose_name='Close/Share'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='open',
            field=models.DateField(blank=True, default=datetime.datetime.now, verbose_name='Open Date'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='open_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='Open/Share'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='quantity',
            field=models.IntegerField(default=0, verbose_name='Quantity'),
        ),
    ]
