# Generated by Django 2.2.5 on 2020-08-23 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InvestmentApp', '0006_auto_20200821_1719'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='watch',
        ),
        migrations.AlterField(
            model_name='stock',
            name='link',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Stock/Fund Website'),
        ),
    ]
