# Generated by Django 2.2.5 on 2020-08-23 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InvestmentApp', '0007_auto_20200822_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='category',
            field=models.CharField(choices=[('S', 'Stock'), ('M', 'Mutual Fund'), ('I', 'Index Fund'), ('E', 'ETF')], default='S', max_length=1, verbose_name='Category'),
        ),
    ]
