# Generated by Django 2.2.5 on 2020-08-25 20:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InvestmentApp', '0012_auto_20200824_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='link',
            field=models.CharField(blank=True, default='', max_length=200, null=True, validators=[django.core.validators.URLValidator], verbose_name='Website'),
        ),
    ]
