# Generated by Django 2.2.5 on 2020-08-26 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InvestmentApp', '0013_auto_20200825_1317'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stock',
            options={'ordering': ['name'], 'verbose_name_plural': 'Stocks'},
        ),
    ]
